---
- name: Google DNS for resolv.conf
  hosts: all
 
  tasks:
 
  - name: Google DNS for resolv.conf
    get_url: url=https://raw.githubusercontent.com/evanbills/std-build-files/master/resolv.conf dest=/etc/resolv.conf mode=0644
